import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import NavbarComponent from "./components/Navbar";
import "./globals.css";
import Footer from "./components/Footer";

const poppins = Poppins({
  variable: "--font-primary",
  weight: ["400", "600"],
  subsets: ["latin"],
  display: "swap",
});

const restora = localFont({
  src: "../public/Restora.woff2",
  variable: "--font-title",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Flowbite React Template Next.js",
  description: "Generated by create-flowbite-react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${restora.variable} ${poppins.variable} antialiased`}>
        {/* <ThemeInit /> */}
        <NavbarComponent />
        {children}
        <Footer />
      </body>
    </html>
  );
}
